name: Code quality

on:
    push:
    pull_request:

jobs:
    code_quality:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Biome
              uses: biomejs/setup-biome@v2
              with:
                  version: latest
            - name: Check code
              run: biome check
            - name: Lint code
              run: biome lint
            - name: Format code
              run: biome format
